/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DummyJSON Products (Typed)
 * OpenAPI spec version: 1.0.0
 */
export type CategoryList = string[];

export interface AddProductRequest {
  title: string;
  description?: string;
  price?: number;
  discountPercentage?: number;
  rating?: number;
  stock?: number;
  brand?: string;
  category?: string;
  thumbnail?: string;
  images?: string[];
}

export interface Product {
  id: number;
  title: string;
  description?: string;
  price?: number;
  discountPercentage?: number;
  rating?: number;
  stock?: number;
  brand?: string;
  category?: string;
  thumbnail?: string;
  images?: string[];
}

