/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DummyJSON Products (Typed)
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddProductRequest,
  CategoryList,
  Product
} from './dummyJSONProductsTyped.schemas';

import { customInstance } from '../custom-instance';





/**
 * @summary Get product category list
 */
export const getProductsCategoryList = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<CategoryList>(
      {url: `/products/category-list`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductsCategoryListQueryKey = () => {
    return [
    `/products/category-list`
    ] as const;
    }

    
export const getGetProductsCategoryListQueryOptions = <TData = Awaited<ReturnType<typeof getProductsCategoryList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsCategoryListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsCategoryList>>> = ({ signal }) => getProductsCategoryList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsCategoryListQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsCategoryList>>>
export type GetProductsCategoryListQueryError = unknown


export function useGetProductsCategoryList<TData = Awaited<ReturnType<typeof getProductsCategoryList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsCategoryList>>,
          TError,
          Awaited<ReturnType<typeof getProductsCategoryList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsCategoryList<TData = Awaited<ReturnType<typeof getProductsCategoryList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsCategoryList>>,
          TError,
          Awaited<ReturnType<typeof getProductsCategoryList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsCategoryList<TData = Awaited<ReturnType<typeof getProductsCategoryList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product category list
 */

export function useGetProductsCategoryList<TData = Awaited<ReturnType<typeof getProductsCategoryList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsCategoryList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsCategoryListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add a new product (mock)
 */
export const addProduct = (
    addProductRequest: AddProductRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Product>(
      {url: `/products/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addProductRequest, signal
    },
      );
    }
  


export const getAddProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: AddProductRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: AddProductRequest}, TContext> => {

const mutationKey = ['addProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addProduct>>, {data: AddProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  addProduct(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddProductMutationResult = NonNullable<Awaited<ReturnType<typeof addProduct>>>
    export type AddProductMutationBody = AddProductRequest
    export type AddProductMutationError = unknown

    /**
 * @summary Add a new product (mock)
 */
export const useAddProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: AddProductRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addProduct>>,
        TError,
        {data: AddProductRequest},
        TContext
      > => {

      const mutationOptions = getAddProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    